<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <Deterministic>true</Deterministic>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\NINA\Resources\ninasplash.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NINA.Core\NINA.Core.csproj" />
    <ProjectReference Include="..\NINA.Profile\NINA.Profile.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fastenshtein" Version="1.0.11" />
    <PackageReference Include="Nito.AsyncEx.Context" Version="5.1.2" />
    <PackageReference Include="Nito.Disposables" Version="2.5.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.9" />
  </ItemGroup>
</Project>
